# Generated by Django 3.0.7 on 2026-07-30 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_actors_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDisplayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_director', models.BooleanField(default=True)),
                ('show_author', models.BooleanField(default=True)),
                ('show_actor', models.BooleanField(default=True)),
                ('show_description', models.BooleanField(default=True)),
                ('show_duration', models.BooleanField(default=True)),
                ('show_release_year', models.BooleanField(default=True)),
                ('show_price', models.BooleanField(default=True)),
                ('show_genre', models.BooleanField(default=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_config', to='movies.Movie')),
            ],
        ),
    ]
