# Generated by Django 3.0.7 on 2026-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_franja_reservaseat_person_name'),
        ('movies', '0008_moviedisplayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='franjas',
            field=models.ManyToManyField(blank=True, related_name='movies', to='reservations.Franja'),
        ),
    ]
