# Generated by Django 3.0.7 on 2026-07-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='funciones', to='reservations.Format'),
        ),
    ]
