# Generated by Django 3.0.7 on 2026-08-17 04:43

from django.db import migrations, models


def backfill_person_name(apps, schema_editor):
    ReservaSeat = apps.get_model("reservations", "ReservaSeat")
    for reserva_seat in ReservaSeat.objects.filter(person_name=""):
        username = getattr(reserva_seat.reserva.user, "username", "") or ""
        reserva_seat.person_name = username
        reserva_seat.save(update_fields=["person_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_funcion_formats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='reservaseat',
            name='person_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.RunPython(backfill_person_name, migrations.RunPython.noop),
    ]
