# Generated by Django 3.0.7 on 2026-08-17

from django.db import migrations, models
import django.db.models.deletion


def backfill_cines(apps, schema_editor):
    Sala = apps.get_model("reservations", "Sala")
    Cine = apps.get_model("reservations", "Cine")
    counters = {}
    for sala in Sala.objects.order_by("id"):
        raw = (sala.name or "").strip()
        raw = raw.replace("SALA ", "").strip() or "Cine General"
        cine, _ = Cine.objects.get_or_create(name=raw)
        counters[cine.id] = counters.get(cine.id, 0) + 1
        sala.cine = cine
        sala.number = counters[cine.id]
        sala.save(update_fields=["cine", "number"])


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_franja_reservaseat_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='cine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='reservations.Cine'),
        ),
        migrations.AddField(
            model_name='sala',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_cines, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sala',
            name='name',
        ),
        migrations.AlterField(
            model_name='sala',
            name='cine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='reservations.Cine'),
        ),
    ]
