# Generated by Django 3.0.7 on 2026-08-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_cine_sala_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['cine', 'number']},
        ),
        migrations.AlterField(
            model_name='sala',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('cine', 'number')},
        ),
    ]
