# Generated by Django 3.0.7 on 2026-07-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_migrate_actor_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
